name: Deploy SILAPER Application

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Create .env file
              run: echo "PORT=${{ secrets.PORT }}" >> .env
            - name: Login to Docker HUB
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build docker image
              run: docker build -t marcellinus123/silaper-app .
            - name: Push image to docker hub
              run: docker push marcellinus123/silaper-app:latest
    deploy:
      needs: build
      runs-on: self-hosted
      steps:
        - name: Pull docker image
          run: docker pull marcellinus123/silaper-app:latest
        - name: Delete old container
          run: docker rm -f silaper-app-container  
        - name: Run docker container          
          run: docker run -d -p 4040:4040 --name silaper-app-container marcellinus123/silaper-app